# ama2/backend/app/core/constants.py

RANDOM_SEED = 42

# Confidence levels
CONFIDENCE_SAFE = "safe"
CONFIDENCE_UNCERTAIN = "uncertain"
CONFIDENCE_UNSAFE = "unsafe"

# Problem types
PROBLEM_CLASSIFICATION = "classification"
PROBLEM_REGRESSION = "regression"
PROBLEM_TIMESERIES = "timeseries"

# Risk Levels
RISK_CRITICAL = "critical"
RISK_WARNING = "warning"
RISK_INFO = "info"

# Risk Codes
LEAKAGE_SUSPECTED = "LEAKAGE_SUSPECTED"
TINY_DATASET = "TINY_DATASET"
DRIFT_DETECTED = "DRIFT_DETECTED"
SCHEMA_DTYPE_MISMATCH = "SCHEMA_DTYPE_MISMATCH"
UNSTABLE_CV = "UNSTABLE_CV"
SUSPICIOUS_AUC = "SUSPICIOUS_AUC"
DOMINANT_FEATURE = "DOMINANT_FEATURE"
HIGH_MISSING_RATE = "HIGH_MISSING_RATE"
CONSTANT_COLUMN = "CONSTANT_COLUMN"
HIGH_DUPLICATE_RATIO = "HIGH_DUPLICATE_RATIO"
MEMORY_BUDGET = "MEMORY_BUDGET"
MISSING_COLUMN_NAMES = "MISSING_COLUMN_NAMES"
CLASS_IMBALANCE = "CLASS_IMBALANCE"
